# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the low-density software chooser
---
mode: required

method: legacy

labels:
    step: "Bootloader"
    step[zh_CN]: "引导加载程序"
    step[ru]: "Загрузчик"

default: grub

items:
    - id: grub
      name: "GRUB"
      description: "GRUB is the oldest of the available boot managers. It has a very large feature set, works on almost every machine, and remains the most widely used Linux boot manager. Tip: Choose GRUB if you need encrypted /boot, BIOS compatibility, or want Btrfs snapshots with a stable, mature boot manager."
      description[zh_CN]: "GRUB 是可用的引导管理器中最古老的一个。它具有非常大的功能集，几乎在每台机器上都能工作，并且仍然是最广泛使用的 Linux 引导管理器。提示：如果您需要加密的 /boot、BIOS 兼容性，或者想要一个稳定、成熟的引导管理器来使用 Btrfs 快照，请选择 GRUB。"

    - id: systemd-boot
      name: "systemd-boot"
      efiOnly: true
      description: "Part of the systemd family, systemd-boot was created to be as simple as possible. This simple yet efficient design ensures it is reliable and fast, but it comes at the cost of advanced features supported by other boot managers. Tip: Choose systemd-boot if you prefer the simplest setup and don’t require snapshots or advanced features. It’s also the most reliable fallback for MSI motherboards with UEFI issues."
      description[zh_CN]: "作为 systemd 家族的一部分，systemd-boot 的设计尽可能简单。这种简单而高效的设计确保了它的可靠性和速度，但代价是缺乏其他引导管理器支持的高级功能。提示：如果您更喜欢最简单的设置，并且不需要快照或高级功能，请选择 systemd-boot。它也是 MSI 主板具有 UEFI 问题时最可靠的回退选项。"
