# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
### pacstrap Module
#
# This module installs the base system and then copies files
# into the installation that will be used in the installed system
#

---
# basePackages is an array of package names to pass to pacstrap
#
basePackages:
  - base
  - base-devel
  - linux-firmware
  - btrfs-progs
  - networkmanager
  - vim
  - sudo
  - grub
  - efibootmgr
  - intel-ucode
  - amd-ucode
  - sof-firmware
  - lvm2
  - man-db
  - man-pages
  - plymouth
  - lsb-release
  - f2fs-tools
  - e2fsprogs
  - xfsprogs
  - jfsutils
  - fish


#
# postInstallFiles is an array of file names which will be copied into the system
#
# The paths should be relative to the host and the files will be copied to the
# location in the installed system
#
postInstallFiles:
  - "/etc/pacman.conf"
