# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# pacstrap replacement using shellprocess.
# Replaces the pacstrap C++ module which is not installed.
---
dontChroot: true
timeout: 600

script:
    - "pacstrap ${ROOT} base base-devel linux linux-firmware btrfs-progs networkmanager vim sudo grub efibootmgr intel-ucode amd-ucode sof-firmware lvm2 man-db man-pages plymouth lsb-release f2fs-tools e2fsprogs xfsprogs jfsutils fish mkinitcpio"
    - "cp /etc/pacman.conf ${ROOT}/etc/pacman.conf"
